### ISSUE TITLE
Allow use ea4_main.local instead ea4_main.default

### ISSUE THREAD

**Issue by shakaran** [CpanelInc/ea-apache2-config#2]
I am using nginx over apache and I have to customize the file under _/var/cpanel/templates/apache2_4/ea4_main.default_ the problem is that this file gets updated and regenerated in each apache update.

For example [in this line](https://github.com/CpanelInc/ea-apache2-config/blob/master/SOURCES/ea4_main.default#L237), I am changing:

```
LogFormat "%h %l %u %t \"%r\" %>s %b" common
LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
```

For:

```
LogFormat "%a %l %u %t \"%r\" %>s %b" common
LogFormat "%a %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
```

Notice the %h by %a

I even generate custom logs like:

```
LogFormat "%a %l %u %t %{Host}i \"%r\" \"?%q\" %>s %b" common_company
LogFormat "%a %l %u %t %{Host}i \"%r\" \"?%q\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined_company
CustomLog "logs/access_log_company" common_company
CustomLog "logs/access_log_company_combined" combined_company
```

So I don't have a easy way to modify this and keep as permanent at this moment since cpanel doesn't allow a easy customization for this file (only config files below from this). Coud you allow a fille ea4_main.local with this?

Regards
Ángel Guzmán Maeso

**Comment by HoustonDad** [comment]
Hi,

Using ea4_main.local is already possible with EA4. Are you having issues where it's not? This may require a ticket.

**Comment by shakaran** [comment]
@JPerkster oh thanks! I was thinking that it would not possible. I gonna try with:

`cp -rf /var/cpanel/templates/apache2_4/ea4_main.{default,local}`

So I get a exact copy from default and I will see if in further update I lost the changes. 

Probably I get this missunderstanding because [the docs](https://documentation.cpanel.net/display/EA/Custom+Templates) doesn't speak clearly about ea4_main.default (other files are mentioned, but not ea4_main.default)

I think that this issue could be closed if you consider that updating the docs could help.

**Comment by HoustonDad** [comment]
Howdy,

Thanks, we'll get those docs updated!

**Comment by henriqueccruz** [comment]
I'm trying to redirect all Webmail requests to a custom subdomain and edited the proper entries in ea4_main.local. But, no matter what I do, the webmail ProxyPass entry still gets overriden by the default record: 127.0.0.1:2095.

I even tried to edit ea4_main.default, but the same behavior occurs whenever httpd.conf gets updated. Is this expected?

Thanks.
